# Generated by Django 4.2.27 on 2026-01-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_user(apps, schema_editor):
    """Create a default user for existing expenses if none exists"""
    User = apps.get_model('auth', 'User')
    Expense = apps.get_model('tracker', 'Expense')
    
    # Check if there are any expenses
    if Expense.objects.exists():
        # Create or get a default user
        user, created = User.objects.get_or_create(
            username='default_user',
            defaults={
                'email': 'default@example.com',
                'is_active': True,
            }
        )
        # Assign all existing expenses to this user
        Expense.objects.filter(user__isnull=True).update(user=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        # Add new category choices to Expense model
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(
                choices=[
                    ('Food', 'Food'),
                    ('Travel', 'Travel'),
                    ('Shopping', 'Shopping'),
                    ('Bills', 'Bills'),
                    ('Entertainment', 'Entertainment'),
                    ('Health', 'Health'),
                    ('Education', 'Education'),
                    ('Other', 'Other'),
                ],
                max_length=20
            ),
        ),
        
        # Add user field to Expense (nullable first)
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expenses',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Create default user and assign expenses
        migrations.RunPython(create_default_user, reverse_code=migrations.RunPython.noop),
        
        # Make user field non-nullable
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expenses',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        
        # Add timestamp fields to Expense
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Create Budget model
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(
                    choices=[
                        ('Food', 'Food'),
                        ('Travel', 'Travel'),
                        ('Shopping', 'Shopping'),
                        ('Bills', 'Bills'),
                        ('Entertainment', 'Entertainment'),
                        ('Health', 'Health'),
                        ('Education', 'Education'),
                        ('Other', 'Other'),
                    ],
                    max_length=20
                )),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('user', 'category', 'month')},
            },
        ),
        
        # Create UserProfile model
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('monthly_budget_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
